version: "3.3"
services:
  database:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local